config/routes.rb
Rails.application.routes.draw do
  
  root "home#index"
  get "home/about" => "home#about"
  patch "task/:id" => "tasks#toggle", as: :change_toggle
  get "/favorites" => "favorites#index", as: :favorite_projects

  resources :projects do 
    resources :tasks, only: [:new, :create, :destroy, :edit, :update]
    resources :discussions

    resources :members, only: [:index, :new, :create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy]
  end

  resources :discussions, only: [] do
    resources :comments, only: [:create, :destroy, :new]
  end

  devise_for :users

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :project
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations, dependent: :destroy
  has_many :projects, through: :categorizations
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  #associations
  belongs_to :user
  belongs_to :discussion

  #validations
  validates :body, presence: true
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  #associations
  belongs_to :user
  belongs_to :project
  has_many :comments

  #validations
  validates :title, presence: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
  #associations
  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_many :discussions, dependent: :destroy

  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  has_many :members, dependent: :destroy
  has_many :users, through: :members

  has_many :favorites, dependent: :destroy
  has_many :users_favorite, through: :favorites, source: :users

  has_many :project_tags, dependent: :destroy
  has_many :tags, through: :project_tags

  #validations
  validates :title, presence: true, uniqueness: true

  #methods
  def self.search(search)
    if search
      where("title ILIKE '%#{search}%' OR description ILIKE '%#{search}%'")
    else
      unscoped
    end
  end

  # def self.show_non_members(members)
  #   if members
  #     where("user_id NOT IN")
  # end

  self.per_page = 5
end

app/models/project_tag.rb
class ProjectTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :project
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :project_tags, dependent: :destroy
  has_many :projects, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
  #associations
  belongs_to :user
  belongs_to :project

  #validations
  validates :title, presence: true, uniqueness: {scope: :project_id}
end
  

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #associations
  has_many :projects, dependent: :nullify
  has_many :tasks, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :discussions, dependent: :nullify

  has_many :members, dependent: :nullify
  has_many :project_members, through: :members, source: :project

  has_many :favorites, dependent: :nullify
  has_many :favorite_projects, through: :favorites, source: :project
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  respond_to :js
  
  def index
    @discussion = Discussion.new
  end

  def new
    @project = Project.find params[:project_id]
    @discussion = Discussion.new
  end

  def create
    @project = Project.find params[:project_id]
    @discussion = @project.discussions.new params.require(:discussion).permit(:title, :description)
    @discussion.user_id = current_user.id
    if @discussion.save
      respond_with(@project, @discussion)
    end
      #redirect_to project_path(@project)
    
  end

  def show
    @discussion = Discussion.find params[:id]
    @comment = @discussion.comments.new
    @comments = @discussion.comments.all.order(:updated_at).reverse
  end

  def destroy
    @discussion = Discussion.find params[:id]
    
    @discussion.destroy

    respond_with()
    #redirect_to project_path(@discussion.project_id), alert: "Discussion deleted"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @project = Project.new
    else
      redirect_to new_user_session_path
    end
  end

  def about
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :js, :html

  before_action :task_id, only: [:new, :destroy, :edit, :update, :toggle]
  before_action :project_id, only: [:create, :destroy, :edit, :update]

  

  def new
    @task = @project.tasks.new
  end

  def create
    @task = @project.tasks.new task_params
    @task.user_id = current_user.id
    @task.status = false #you cannot create a finished project. That would not make sense
    if @task.save
      respond_with(@project)
      #redirect_to project_path(@project), notice: "Task created successfully"
    else
      @project.tasks.reload
      redirect_to project_path(@project), alert: "Invalid task!"
    end
  end

  def destroy
    @task.destroy
    respond_with()
    #redirect_to project_path(@project), notice: "Task deleted"
  end

  def edit
  end

  def update
    @task.update task_params
    redirect_to project_path(@project), notice: "Task updated"
  end

  #toggle button
  def toggle
    if @task.status == true
      @task.status = false
    else
      @task.status = true
      if @task.user_id != current_user.id
        ProjectMailer.task_done(@task, current_user).deliver_later
      end
    end
    @task.save
    # redirect_to project_path(@task.project_id)
    respond_with()
  end

  #private methods begin
  private
  def task_params
    params.require(:task).permit(:title, :due_date)
  end

  def task_id
    @task = Task.find params[:id]
  end

  def project_id
    @project = Project.find params[:project_id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/project_tags_helper.rb
module ProjectTagsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/discussions/_index.html.erb
  <h4>Discussions:</h4>
  <a id="addDiscussion" ><span class="glyphicon glyphicon-plus"></span></a>
    <a id="minusDiscussion"><span class="glyphicon glyphicon-minus"></span></a>

  <div class="well newDiscussion" style="display:none;">
    <%= render 'discussions/new' %>
  </div>

  
  <table class="table table-striped" id="discussionTable">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Added by</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @discussions.each do |discussion| %>
       <%= render partial: 'discussions/row', locals: { discussion: discussion } %>
      <% end %>
    </tbody>

  </table>

app/views/discussions/_new.html.erb
<h3>Create a new discussion:</h3>

<%= form_for [@project, @discussion],remote: true do |d| %>
  <%= d.label :title %>
  <%= d.text_field :title %>
  <br>
  <%= d.label :description %>
  <%= d.text_field :description %>
  <br>
  <%= d.submit %>
<% end %>

app/views/discussions/_row.html.erb
<tr id="<%= dom_id( discussion )%>">
  <td><%= link_to discussion.title, project_discussion_path(@project, discussion) %></td>
  <td><%= discussion.description %></td>
  <td><%= (User.find discussion.user_id).first_name.capitalize %> </td>
  <td>
    <%= link_to "Delete Discussion", project_discussion_path(@project, discussion), method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
  </td>
</tr>

app/views/discussions/create.js.erb
//put the new discussion on the top of the discussion table
$('#discussionTable tbody').prepend(' <%= j render partial: "discussions/row", locals: {discussion: @discussion} %> ');
$('#discussion_title').val('');
$('#discussion_description').val('');

//hide the new discussion partial and toggle the buttons
$('.newDiscussion').fadeOut();
$('#minusDiscussion').fadeOut(function() {
  $('#addDiscussion').fadeIn();
});

app/views/discussions/destroy.js.erb
$('#<%= dom_id(@discussion) %>').fadeOut();

app/views/discussions/new.html.erb
<h3>Create a new discussion:</h3>

<%= form_for [@project, @discussion] do |d| %>
  <%= d.label :title %>
  <%= d.text_field :title %>
  <br>
  <%= d.label :description %>
  <%= d.text_field :description %>
  <br>
  <%= d.submit %>
<% end %>

app/views/discussions/show.html.erb
<div class="well">
  <center>
    <h2><%= @discussion.title %></h2>
    <p><%= @discussion.description %></p>
  </center>
</div>

<div class="well well-sm">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Comments:</th>
      <th><a id="addComment" ><span class="glyphicon glyphicon-plus"></span></a>
    <a id="minusComment"><span class="glyphicon glyphicon-minus"></span></a></th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <%= render partial: 'comments/row', locals: {comment: comment} %>
    <% end %>
  </tbody>
</table>
</div>

<div class="newComment" style="display:none;">
  <%= render 'comments/new' %>
</div>