config/routes.rb
Rails.application.routes.draw do
  
  root "home#index"
  get "home/about" => "home#about"
  patch "task/:id" => "tasks#toggle", as: :change_toggle
  get "/favorites" => "favorites#index", as: :favorite_projects

  resources :projects do 
    resources :tasks, only: [:new, :create, :destroy, :edit, :update]
    resources :discussions

    resources :members, only: [:index, :new, :create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy]
  end

  resources :discussions, only: [] do
    resources :comments, only: [:create, :destroy, :new]
  end

  devise_for :users

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :project
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations, dependent: :destroy
  has_many :projects, through: :categorizations
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  #associations
  belongs_to :user
  belongs_to :discussion

  #validations
  validates :body, presence: true
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  #associations
  belongs_to :user
  belongs_to :project
  has_many :comments

  #validations
  validates :title, presence: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
  #associations
  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_many :discussions, dependent: :destroy

  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  has_many :members, dependent: :destroy
  has_many :users, through: :members

  has_many :favorites, dependent: :destroy
  has_many :users_favorite, through: :favorites, source: :users

  has_many :project_tags, dependent: :destroy
  has_many :tags, through: :project_tags

  #validations
  validates :title, presence: true, uniqueness: true

  #methods
  def self.search(search)
    if search
      where("title ILIKE '%#{search}%' OR description ILIKE '%#{search}%'")
    else
      unscoped
    end
  end

  # def self.show_non_members(members)
  #   if members
  #     where("user_id NOT IN")
  # end

  self.per_page = 5
end

app/models/project_tag.rb
class ProjectTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :project
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :project_tags, dependent: :destroy
  has_many :projects, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
  #associations
  belongs_to :user
  belongs_to :project

  #validations
  validates :title, presence: true, uniqueness: {scope: :project_id}
end
  

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #associations
  has_many :projects, dependent: :nullify
  has_many :tasks, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :discussions, dependent: :nullify

  has_many :members, dependent: :nullify
  has_many :project_members, through: :members, source: :project

  has_many :favorites, dependent: :nullify
  has_many :favorite_projects, through: :favorites, source: :project
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @project = Project.new
    else
      redirect_to new_user_session_path
    end
  end

  def about
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :project_id, only: [:show, :edit, :update, :destroy]
  def index
    if params[:search].present?
      @projects = Project.page(params[:page]).search params[:search]
    else
      @projects = Project.page(params[:page])
      @projects = @projects.all.order(:due_date)
    end
    @project = Project.new 
    @favorites = Project.find current_user.favorites.map(&:project_id)
  end

  def new
    @project = Project.new 
  end

  def create
    @project = Project.new project_params
    @project.user_id = current_user.id
    if @project.save
      redirect_to projects_path, notice: "Project created successfully"
    else
      flash[:alert] = "Create project failed. Please try again"
      redirect_to projects_path
    end
  end

  def show
    @task = Task.new
    @discussion = Discussion.new
    @user = User.find @project.user_id
    @tasks = @project.tasks.order(:updated_at).reverse
    @discussions = @project.discussions.all.order(:updated_at).reverse
  end

  def edit
  end

  def update
    @project.update project_params
    redirect_to project_path(@project), notice: "Project updated"
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: "Project deleted"
  end

  

  private
  def project_params
    params.require(:project).permit(:title, :description, :due_date, :finished, 
          {category_ids:[]}, {user_ids: []}, {tag_ids: []})
  end

  def project_id
    @project = Project.find params[:id]
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :js, :html

  before_action :task_id, only: [:new, :destroy, :edit, :update, :toggle]
  before_action :project_id, only: [:create, :destroy, :edit, :update]

  

  def new
    @task = @project.tasks.new
  end

  def create
    @task = @project.tasks.new task_params
    @task.user_id = current_user.id
    @task.status = false #you cannot create a finished project. That would not make sense
    if @task.save
      respond_with(@project)
      #redirect_to project_path(@project), notice: "Task created successfully"
    else
      @project.tasks.reload
      redirect_to project_path(@project), alert: "Invalid task!"
    end
  end

  def destroy
    @task.destroy
    respond_with()
    #redirect_to project_path(@project), notice: "Task deleted"
  end

  def edit
  end

  def update
    @task.update task_params
    redirect_to project_path(@project), notice: "Task updated"
  end

  #toggle button
  def toggle
    if @task.status == true
      @task.status = false
    else
      @task.status = true
      if @task.user_id != current_user.id
        ProjectMailer.task_done(@task, current_user).deliver_later
      end
    end
    @task.save
    # redirect_to project_path(@task.project_id)
    respond_with()
  end

  #private methods begin
  private
  def task_params
    params.require(:task).permit(:title, :due_date)
  end

  def task_id
    @task = Task.find params[:id]
  end

  def project_id
    @project = Project.find params[:project_id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/project_tags_helper.rb
module ProjectTagsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/projects/_form.html.erb
  <%= form_for @project do |p| %>
    <div class="field">
      <%= p.text_field :title, class:"form-control", placeholder: "Project Title"%>
    </div>
    <br>

    <div class="field">
    <%= p.label :category %><br>
    <%= p.collection_check_boxes :category_ids, Category.all, :id, :name, class:"form-control" %>
    </div>
    <br>

    <div class="field">
    <%= p.text_area :description, class:"form-control", placeholder: "Project Description" %>
    </div>
    <br>

    <div class="field">
    <%= p.label :due_date %>
    <%= p.date_field :due_date, class:"form-control" %>
    </div>
    <br>

    <%= p.label :members %><br>
    <%= p.collection_check_boxes :user_ids, User.all, :id, :first_name %>
    <br><br>

    <%= p.label :tags %><br>
    <%= p.collection_check_boxes :tag_ids, Tag.all, :id, :name, class:"form-control" %>
    <br>

    <%= p.submit %>
  <% end %>

app/views/projects/_new.html.erb
<h4> Add Project </h4>

<%= render 'projects/form' %>

app/views/projects/_table.html.erb
<tr>
  <td><%= link_to p.title, project_path(p)%></td>
  <td><%= p.categories.map(&:name).join(', ') %></td>
  <td><%= p.description %></td>
  <td><%= p.due_date %></td>
  <td>
    <% if p.user_id == current_user.id %>
      <%= link_to "EDIT", edit_project_path(p), class: "btn btn-default" %>
      <%= link_to "DELETE", project_path(p), 
            method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default" %>
    <% end %>
  </td>
</tr>

app/views/projects/edit.html.erb
<h2> EDIT THIS PROJECT PAGE </h2>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class="row">

  <div class="col-md-2"><h2> PROJECTS </h2></div>
  <div class="col-md-1"  style="margin-top: 32px;">
    <a id="add" ><span class="glyphicon glyphicon-plus"></span></a>
    <a id="minus"><span class="glyphicon glyphicon-minus"></span></a>
  </div>
  <div class="col-md-9" style="margin-top: 32px;">
    <a id="favorites">Favorites</a>
  </div>
</div>

<div class="newProject" style="display:none;">
  <%= render 'new' %>
</div>

<div id="favoriteIndex" style="display: none;">
  <% if @favorites.length < 1%>
    <h3> You have not favorited projects yet </h3>
  <% else %>
    <h6> Favorite Index </h6>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Category</th>
          <th>Description</th>
          <th>Due Date</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @favorites.each do |favorite| %>
          <%= render 'projects/table', p: favorite %>
      <% end %>
      </tbody>
    </table>
  <% end %>
</div>

<br>

<table class="table table-striped" id="projectIndex">
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Description</th>
      <th>Due Date</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <%= render 'projects/table', p: project %>
    <% end %> 
  </tbody>

</table>



<%= will_paginate @projects %>

app/views/projects/new.html.erb
<h2>New Project Page </h2>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="well">
  <center>
    <h2><%= @project.title %></h2>

    <strong>Description:</strong>
    <p>&emsp;<%= @project.description %></p>
    <strong>Category:</strong>&emsp;<%= @project.categories.map(&:name).join(', ') %>
    <br>
    <strong>Due Date:</strong>&emsp;<%= @project.due_date %>
    <br>
    
    <% if @project.user_id.present? %>
      <strong>Created By:</strong> &emsp;<%= @user.first_name.capitalize %>
      <br>
    <% end %>

    <% if @project.members.present? %>
      <strong>Members: </strong>
        <%= User.find( @project.members.map(&:user_id) ).map(&:first_name).join(', ') %>
      <br>
    <% end %>
    <br>

    <% if @project.tags.present? %>
      <strong>Tags: </strong>
        <%= @project.tags.map(&:name).join(', ') %>
      <br>
    <% end %>
    <br>

    <% if @project.user_id != current_user.id %>
      <% if (@project.favorites.map(&:user_id)).include?(current_user.id) %>
        <% @favorite = Favorite.where(project_id: @project.id, user_id: current_user.id).first %>
        <%= link_to "unFavorite", project_favorite_path(@project, @favorite), method: :delete %>
      <% else %>
        <%= link_to "Favorite", project_favorites_path(@project), method: :post %>
      <% end %>
    <% end %>

  </center>

  <br>
  
  <%= render "tasks/index" %>
  
  
  <%= render 'discussions/index' %>
  

</div>