config/routes.rb
Rails.application.routes.draw do
  
  root "home#index"
  get "home/about" => "home#about"
  patch "task/:id" => "tasks#toggle", as: :change_toggle
  get "/favorites" => "favorites#index", as: :favorite_projects

  resources :projects do 
    resources :tasks, only: [:new, :create, :destroy, :edit, :update]
    resources :discussions

    resources :members, only: [:index, :new, :create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy]
  end

  resources :discussions, only: [] do
    resources :comments, only: [:create, :destroy, :new]
  end

  devise_for :users

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :project
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations, dependent: :destroy
  has_many :projects, through: :categorizations
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  #associations
  belongs_to :user
  belongs_to :discussion

  #validations
  validates :body, presence: true
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  #associations
  belongs_to :user
  belongs_to :project
  has_many :comments

  #validations
  validates :title, presence: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
  #associations
  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_many :discussions, dependent: :destroy

  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  has_many :members, dependent: :destroy
  has_many :users, through: :members

  has_many :favorites, dependent: :destroy
  has_many :users_favorite, through: :favorites, source: :users

  has_many :project_tags, dependent: :destroy
  has_many :tags, through: :project_tags

  #validations
  validates :title, presence: true, uniqueness: true

  #methods
  def self.search(search)
    if search
      where("title ILIKE '%#{search}%' OR description ILIKE '%#{search}%'")
    else
      unscoped
    end
  end

  # def self.show_non_members(members)
  #   if members
  #     where("user_id NOT IN")
  # end

  self.per_page = 5
end

app/models/project_tag.rb
class ProjectTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :project
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :project_tags, dependent: :destroy
  has_many :projects, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
  #associations
  belongs_to :user
  belongs_to :project

  #validations
  validates :title, presence: true, uniqueness: {scope: :project_id}
end
  

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #associations
  has_many :projects, dependent: :nullify
  has_many :tasks, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :discussions, dependent: :nullify

  has_many :members, dependent: :nullify
  has_many :project_members, through: :members, source: :project

  has_many :favorites, dependent: :nullify
  has_many :favorite_projects, through: :favorites, source: :project
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @project = Project.new
    else
      redirect_to new_user_session_path
    end
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_menu.html.erb
<div class="row">
  <div class="col-md-8 ">
    <ul class="nav nav-tabs">
      <li><a href="/">The Home Page</a></li>
      <li><a href="/home/about/">The About Page</a></li>
      <% if user_signed_in? %>
      <li><%= link_to "Projects", projects_path %></li>
      <% end %>
    </ul>
  </div>
      
  <div class="col-md-4">
    <div class="row">
      
      <div class="col-md-7">
        <%= form_tag projects_path, :method => 'get' do %>
          <p style="margin-top:10px;">
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search", :name => nil %>
          </p>
        <% end %>
      </div>

      <div class="col-md-5">
        <% if user_signed_in? %>
          <span style="margin-top:15px;">
            Hello, <%= link_to current_user.first_name.capitalize, edit_user_registration_path %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>  
          </span>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!-- 
is there somewhere - halsey  
kings and queens - brooke fraser 
-->
<!DOCTYPE html>
<html>
<head>
  <title>PMTool</title>
  <%# if user_signed_in? %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%# else %>
    <%#= stylesheet_link_tag 'external', media: 'all' %>
  <%# end %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <% if user_signed_in? %>
        <%= render 'layouts/menu' %>
    <% end %>
        <%= flash[:notice] || flash[:alert]%>
        <%= yield %>
  </div>
</body>
</html>