config/routes.rb
Rails.application.routes.draw do
  
  root "home#index"
  get "home/about" => "home#about"
  patch "task/:id" => "tasks#toggle", as: :change_toggle
  get "/favorites" => "favorites#index", as: :favorite_projects

  resources :projects do 
    resources :tasks, only: [:new, :create, :destroy, :edit, :update]
    resources :discussions

    resources :members, only: [:index, :new, :create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy]
  end

  resources :discussions, only: [] do
    resources :comments, only: [:create, :destroy, :new]
  end

  devise_for :users

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :project
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations, dependent: :destroy
  has_many :projects, through: :categorizations
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  #associations
  belongs_to :user
  belongs_to :discussion

  #validations
  validates :body, presence: true
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  #associations
  belongs_to :user
  belongs_to :project
  has_many :comments

  #validations
  validates :title, presence: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
  #associations
  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_many :discussions, dependent: :destroy

  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  has_many :members, dependent: :destroy
  has_many :users, through: :members

  has_many :favorites, dependent: :destroy
  has_many :users_favorite, through: :favorites, source: :users

  has_many :project_tags, dependent: :destroy
  has_many :tags, through: :project_tags

  #validations
  validates :title, presence: true, uniqueness: true

  #methods
  def self.search(search)
    if search
      where("title ILIKE '%#{search}%' OR description ILIKE '%#{search}%'")
    else
      unscoped
    end
  end

  # def self.show_non_members(members)
  #   if members
  #     where("user_id NOT IN")
  # end

  self.per_page = 5
end

app/models/project_tag.rb
class ProjectTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :project
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :project_tags, dependent: :destroy
  has_many :projects, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
  #associations
  belongs_to :user
  belongs_to :project

  #validations
  validates :title, presence: true, uniqueness: {scope: :project_id}
end
  

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #associations
  has_many :projects, dependent: :nullify
  has_many :tasks, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :discussions, dependent: :nullify

  has_many :members, dependent: :nullify
  has_many :project_members, through: :members, source: :project

  has_many :favorites, dependent: :nullify
  has_many :favorite_projects, through: :favorites, source: :project
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @project = Project.new
    else
      redirect_to new_user_session_path
    end
  end

  def about
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.all 
  end

  def create
  end

  def destroy
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :js, :html

  before_action :task_id, only: [:new, :destroy, :edit, :update, :toggle]
  before_action :project_id, only: [:create, :destroy, :edit, :update]

  

  def new
    @task = @project.tasks.new
  end

  def create
    @task = @project.tasks.new task_params
    @task.user_id = current_user.id
    @task.status = false #you cannot create a finished project. That would not make sense
    if @task.save
      respond_with(@project)
      #redirect_to project_path(@project), notice: "Task created successfully"
    else
      @project.tasks.reload
      redirect_to project_path(@project), alert: "Invalid task!"
    end
  end

  def destroy
    @task.destroy
    respond_with()
    #redirect_to project_path(@project), notice: "Task deleted"
  end

  def edit
  end

  def update
    @task.update task_params
    redirect_to project_path(@project), notice: "Task updated"
  end

  #toggle button
  def toggle
    if @task.status == true
      @task.status = false
    else
      @task.status = true
      if @task.user_id != current_user.id
        ProjectMailer.task_done(@task, current_user).deliver_later
      end
    end
    @task.save
    # redirect_to project_path(@task.project_id)
    respond_with()
  end

  #private methods begin
  private
  def task_params
    params.require(:task).permit(:title, :due_date)
  end

  def task_id
    @task = Task.find params[:id]
  end

  def project_id
    @project = Project.find params[:project_id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/project_tags_helper.rb
module ProjectTagsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/members/index.html.erb
<h2>Member index</h2>

app/views/members/new.html.erb
<h2>add members</h2>

<% form_for @project_members do |member| %>
    <%= member.label :members %>
    <%= member.collection_check_boxes :user_ids, User.all, :id, :first_name %>
    <%= member.submit %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for [@project, @task], remote: true do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <br>
  <%= t.label :due_date %>
  <%= t.date_field :due_date, min: Date.today %>
  <br>
  <%= t.submit %>
<% end %>

app/views/tasks/_index.html.erb
  <h4>Tasks: </h4>
  <a id="addTask" ><span class="glyphicon glyphicon-plus"></span></a>
    <a id="minusTask"><span class="glyphicon glyphicon-minus"></span></a>
  <%= flash[:alert] %>

  <div class="well newTask" style="display:none;">
    <%= render "tasks/new" %>
  </div>


<div class="row">
  <div class="col-md-6" id="pendingTask">
  <h3> Pending Task </h3>
  <table class="table table-striped" id="tasksTable">
    <thead>
      <tr>
        <th>Title</th>
        <th>Due Date</th>
        <th>Added By</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
        <% @tasks.each do |task| %>
          <% if task.status == false %>
          <%= render partial: '/tasks/row', locals: { task: task }%>
          <% end %>
        <% end %> 
    </tbody>
  </table>
  </div>
  <div class="col-md-6" id="doneTask">  
  <h3> Done Task </h3>
  <table class="table table-striped" id="tasksTable">
    <thead>
      <tr>
        <th>Title</th>
        <th>Due Date</th>
        <th>Added By</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
        <% @tasks.each do |task| %>
          <% if task.status == true %>
          <%= render partial: '/tasks/row', locals: { task: task }%>
          <% end %>
        <% end %> 
    </tbody>
  </table>
  </div>
 
</div>

app/views/tasks/_new.html.erb
<h4> Create new task </h4>
<% if @task.errors.any? %>
  <% @task.errors.full_messages.each do |error| %>
  <h3><%= error %></h3>
  <% end %>
<% end %>

<%= render 'tasks/form' %>

app/views/tasks/_row.html.erb
<tr id="<%= dom_id( task ) %>">
  <td><%= task.title %></td>
  <td><%= task.due_date %></td>
  <td><%= (User.find task.user_id).first_name.capitalize %></td>
  <td>

    <% if task.status == true %>
      <%= link_to "DONE", change_toggle_path(task), method: :patch, remote: true %>
    <% else %>
      <%= link_to "NOT DONE", change_toggle_path(task), method: :patch, remote: true %>
    <% end %> 
    |
    <%= link_to "Delete Task", project_task_path(@project, task), 
        method: :delete, data: {confirm: "are you sure?"}, remote: true %> |
    <%= link_to "Edit Task", edit_project_task_path(@project, task) %>
  </td>
</tr>

app/views/tasks/create.js.erb
//put the new task in the pending table.
//new tasks are always not done. 
$('#pendingTask tbody').prepend(' <%= j render partial: "tasks/row", locals: {task: @task} %> ');
$('#task_title').val('');
$('#task_due_date').val('');

//fade out the new task partial and change the button
$('.newTask').fadeOut();
$('#minusTask').fadeOut(function() {
  $('#addTask').fadeIn();
});

app/views/tasks/destroy.js.erb
$('#<%= dom_id(@task) %>').fadeOut();

app/views/tasks/edit.html.erb
<h2> EDIT PAGE </h2>

<%= render 'form' %>

app/views/tasks/new.html.erb
<h2> NEW PAGE </h2>
<% if @task.errors.any? %>
  <% @task.errors.full_messages.each do |error| %>
  <h3><%= error %></h3>
  <% end %>
<% end %>

<%= render 'form' %>

app/views/tasks/toggle.js.erb
if( $('#<%= dom_id(@task) %> td a').eq(0).html() === 'DONE' ){
  $('#<%= dom_id(@task) %> ').eq(0).fadeOut(function() {
    $('#<%= dom_id(@task) %> td a').eq(0).html('NOT DONE')
    $('#pendingTask tbody').prepend($('#<%= dom_id(@task) %> ').fadeIn() );
  });
  
}
else {
 $('#<%= dom_id(@task) %> ').eq(0).fadeOut(function() {
    $('#<%= dom_id(@task) %> td a').eq(0).html('DONE')
    $('#doneTask tbody').prepend($('#<%= dom_id(@task) %> ').fadeIn() );
  });
  
}